import { mantineHtmlProps } from "@mantine/core";
import MantineProvider from "./MantineProvider";
import { Caveat } from "next/font/google";

export const caveat = Caveat({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-caveat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={caveat.variable} {...mantineHtmlProps}>
      <body>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
