import { mantineHtmlProps } from "@mantine/core";
import MantineProvider from "./MantineProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <body>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
